routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home','HomeController@index')->name('dashboard.index')->middleware('auth');

Auth::routes();
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');








Route::middleware(['auth'])->group(function(){
Route::get('/dashboard','HomeController@index')->name('dashboard.index');

Route::resource('teams','TeamsController');


Route::resource('users','UsersController')->middleware(['leader']);
Route::post('users/details/{user}','UsersController@details')->name('users.details')->middleware(['leader']);
Route::put('/users/{user}/make-team-member','UsersController@makeTeamMember')->name('users.make-team-member')->middleware(['leader']);
Route::put('/users/{user}/remove-team-member','UsersController@removeTeamMember')->name('users.remove-team-member')->middleware(['leader']);
// Route::resource('teams','TeamsController');

Route::resource('tasks','TasksController');
// Route::get('/mytasks','TasksController@mytasks')->name('tasks.mytasks');
Route::get('/review','TasksController@review')->name('tasks.review')->middleware(['leader']);
// Route::get('/completed/{task}','TasksController@completed')->name('tasks.completed');
Route::get('/resolved/{task}','TasksController@resolved')->name('tasks.resolved')->middleware(['leader']);
Route::get('/unresolved/{task}','TasksController@unresolved')->name('tasks.unresolved')->middleware(['leader']);
Route::post('/tasks/{task}','TasksController@update')->name('tasks.update')->middleware(['leader']);
Route::post('/tasks/assigned/{user}','TasksController@assign')->name('tasks.assign')->middleware(['leader']);
Route::get('/mytasks','TasksController@mytasks')->name('tasks.mytasks');
Route::get('/completed/{task}','TasksController@completed')->name('tasks.completed');
Route::get('/reassign/{task}','TasksController@reassign')->name('tasks.reassign');
Route::get('/poll','TasksController@poll')->name('tasks.poll');
Route::get('/giveup/{task}','TasksController@giveup')->name('tasks.giveup');
Route::get('/claim-task/{task}','TasksController@claim')->name('tasks.claim');
});


?>

app/Task.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Console\Scheduling\Schedule;
use App\Console\Kernel as ConsoleKernal;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['name','status','assigned_on','due_on','completed_on','level','user_id'];

    public function user()
    {
        return $this->belongsTo(\App\User::class);
    }
    public function team()
    {
        return $this->belongsTo(\App\Team::class);
    }
    public function getAssignedDateAttribute(){
        return (Carbon::parse($this->assigned_on))->diffForHumans();
    } 
    public function getDueDateAttribute(){
        return (Carbon::parse($this->due_on))->diffForHumans();
    } 
    public function getCompletedDateAttribute(){
        return (Carbon::parse($this->completed_on))->diffForHumans();
    } 
      
    
    
    public function updateUserEfficiency(User $user , int $points){
        $user->efficiency = $user->efficiency+$points;
        $user->save();
        
    }

    public function updateLeaderEfficiency(User $leader,Task $task){
        
        if($task->level == 0 )
            $points = 1;
        else if($task->level==1)
            $points = 2;
        else if($task->level ==2)
            $points =3;

        $leader->efficiency = $leader->efficiency+$points;
        $leader->save();
    }

    public function giveupEfficiency(User $user,Task $task)
    {
        if($task->level==0)
            $points = 6;
        else if($task->level==1)
            $points = 10;
        else if($task->level == 2)
            $points = 13;

        $user->efficiency = $user->efficiency - $points;
        $user->save();
    }

    public function getEfficientUser(){
        
        $users = User::orderBy("efficiency",'DESC')->where('team_id',auth()->user()->team_id)->where('role','member')->get();
        $newEfficiencyArray = array();
        foreach ($users as $user) {
            $flag = true;
            $totalHours = 0;
            $count = 0;
            $task = Task::all()->where('user_id',$user['id'])->where('status','assigned')->pluck('level');
            
            if($task->count() == 0)
            {
                $eligible = Carbon::now()->diffInDays(Carbon::parse($user->created_at));
                if($eligible >= 30){
                    return $user;   
                }
                $flag = false;            
            }
            
            elseif($flag){
                for($i = 0;$i < $task->count() ; $i++){
                    $level = $task[$i];
                    if($level == 0){$totalHours += 1;}
                    elseif($level == 1){$totalHours += 2;}
                    elseif($level == 2){$totalHours += 3;}
                
                    $newEfficiency = $user['efficiency']/$totalHours;
                    array_push($newEfficiencyArray,$newEfficiency);
                }
            }
        } 
        $userFinal = array_search(max($newEfficiencyArray),$newEfficiencyArray);
        return $users[$userFinal];   
        
    }
    

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'address','dob','team_id','role','designation_id','efficiency'
    ];

    /**designation
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function isLeader()
    {
        return $this->role === 'leader';
    }
    
    /**
     * Relationship methods
     */
    
     public function team()
     {
            return $this->belongsTo(\App\Team::class);
         
     }
     public function tasks()
     {
            return $this->hasMany(\App\Task::class);
         
     }

     public function logs()
     {
            return $this->hasMany(\App\Log::class);
     
     }

     public function designation()
     {
            return $this->belongsTo(\App\Designation::class);
         
     }

     public function getAvatarSmallAttribute(){
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }
    public function getAvatarBigAttribute(){
        $size = 70;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&size={$size}";
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Log;
use App\Notifications\AddedToTeam;
use App\Notifications\RemovedFromTeam;
use App\User;
use App\Task;

use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $users = User::latest('updated_at')->paginate(10);
        $sidebarSection = 'users';
        $sidebarSubSection = '';
        return view('users.index',compact([
           'users',
           'sidebarSection',
           'sidebarSubSection'
        ]));
    }

    public function makeTeamMember(User $user) {
        
        $user->update(['team_id'=>auth()->user()->team_id,'role'=>'member']);
        session()->flash('success', $user->name . ' has been assigned to your team now!');
        $user->notify(new AddedToTeam($user));
        
        return redirect(route('teams.index'))->with('flash_message', 'This is my flash message!');
        //return redirect(route('teams.index'));
    }

    public function removeTeamMember(User $user) {
        
        $user->update(['team_id'=>NULL,'role'=>'NULL']);
        session()->flash('success', $user->name . ' has been removed from your team now!');
        $user->notify(new RemovedFromTeam($user));
        return redirect(route('teams.index'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }

    public function details(User $user){
        $sidebarSection = 'users';
        $sidebarSubSection = '';
        $tasks = Task::where('user_id',$user['id'])->latest('updated_at')->paginate(10);
        $logs = Log::all()->where('user_id',$user['id'])->where('logged_out','!=',NULL);
        $logstasks = Task::all()->where('status','completed')->where('user_id',$user['id']);
        
        return view('users.details',compact([
           'user',
           'tasks',
           'sidebarSection',
           'sidebarSubSection',
           'logs',
           'logstasks'
        ]));
    }
}

resources/views/users/details.blade.php
@extends('dashboard.layout')
@section('title','Ticket Management')
@section('sub-title','Users')

@section('page-level-styles')

    <style>
         .displayNone{
    display:none;
 } 
    </style>
    @endSection

@section('main-content')
<div class="d-flex justify-content-end mb-3">
   
    </div>

        <div class="card">
            <div class="card-header"><img src="{{ $user->avatar_small }}" alt=""> {{$user->name}} </div>

            <div class="card-body">
                <div class="personal-details ">
                    <label for="Team">Team Name : {{$user->team->name}}</label> <br>
                    <label for="Team">Role : {{$user->role}}</label> <br>
                    <label for="Team">Email : {{$user->email}}</label> <br>
                    <label for="Team">DOB : {{$user->dob}}</label> <br>
                    <label for="Team">Address : {{$user->address}}</label><br><br>
                    
                   
                    
                </div>
                @if($user->role == "member")
                <div class="personal-details ">
                    <label for="Team">Total Tasks : {{$tasks->count()}}</label><br>
                    <label for="Team">Active Tasks : {{$tasks->where('status','assigned')->count()}}</label><br>
                    <label for="Team">Completed Tasks: {{$tasks->where('status','resolved')->count()}}</label><br>
                    <label for="Team">Failed Tasks : {{$tasks->where('status','unresolved')->count()}}</label><br><br>
                    <h6 class="text-primary" style="font-weight:600;">Tasks</h6>
                    
                </div>
                
                <table class="table table-bordered">
                    <thead>
                    
                        <th>Task Name</th>
                        <th>Level</th>
                        <th>Status</th>
                        <th>Assigned On</th>
                        <th>Due On</th>    
                        <th>Completed On</th>                
                    </thead>
                    <tbody>
                        @foreach($tasks as $task)
                            <tr>
                                <td>
                                   {{$task->name}}
                                </td>
                                
                                <td>
                                    @if($task->level==0)
                                        Easy
                                    @elseif($task->level==1)
                                        Intermediate
                                    @else
                                        Difficult
                                    @endif
                                </td>
                                <td>
                                    {{$task->status}}
                                </td>
                                
                                <td>
                                    {{$task->assigned_date}}
                                </td>

                                <td>
                                    {{$task->due_date}}
                                </td>

                                <td>
                                @if(($task->status=="assigned" || !$task->status=='unresolved') && !$task->completed_on )
                                    In Progress
                                @elseif($task->status=="unresolved") 
                                    <p class="text-danger">Failed!</p> 
                                    @else
                                    {{$task->completed_date}}
                                @endif 
                                </td>
                            </tr>
                           
                        @endforeach
                        
                    </tbody>
                </table>
                @endif
                {{$tasks->links()}}
                <div class="d-flex justify-content-around m-5 ">
                    <button class="btn btn-primary" id="adv-details">View Advanced Details &nbsp; <span id="innerdetails" class="displayNone">  <i class="fa fas fa-chevron-down"></i></span></button>
                </div> 

                <table class="table table-bordered displayNone" id="logsTable">
                    <thead>
                    
                        <th>Logged In</th>
                        <th>Logged Out</th>
                        <th>Tasks Completed</th>
                                   
                    </thead>
                    <tbody>
                        @foreach($logs as $log)
                        <tr>

                            <td>{{$log->logged_in}}</td>
                            <td>{{$log->logged_out}}</td>
                            <td>                                
                                @foreach($logstasks as $logstask)
                                
                                    @if((\Carbon\Carbon::parse($logstask->completed_on)->gt(\Carbon\Carbon::parse($log->logged_in))) && (\Carbon\Carbon::parse($logstask->completed_on)->lt(\Carbon\Carbon::parse($log->logged_out))))
                                        <i class="fa fa-star text-warning"></i>
                                    
                                    @endif
                                @endforeach
                            </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    
@endsection

@section('page-level-scripts')

<script>

var table = document.getElementById('logsTable');
var innerdetails = document.getElementById('innerdetails');

var btn = document.getElementById('adv-details');
btn.addEventListener('click',function(){
    setTimeout(function(){
        table.classList.toggle("displayNone");
        innerdetails.classList.toggle("displayNone");
    },500);
    
});

</script>
@endsection

resources/views/users/index.blade.php
@extends('dashboard.layout')
@section('title','Ticket Management')
@section('sub-title','Users')
@section('main-content')

    <div class="card">
        <div class="card-header">Users</div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Team</th>
                    <th>Role</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>
                            <img src="{{ $user->avatar_big }}" alt="">
                            </td>
                            <td>
                                {{$user->name}}
                            </td>
                            <td>
                                {{$user->email}}
                            </td>
                            <td>
                            @if($user->team_id)
                                
                                {{$user->team->name}}
                            @else
                            <p class="text-danger">Currently not assigned</p>
                                @endif
                            </td>
                            <td>
                                @if($user->isLeader())
                                    Leader
                                @else
                                    Member
                                @endif
                            </td>
                            <td>
                                @if(!$user->team_id && $user->tasks->where('status','assigned')->count()==0)
                                    <form action="{{route('users.make-team-member',$user->id)}}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn btn-warning  btn-sm">Add To Team</button>
                                    </form>
                                @endif
                                @if($user->team_id == auth()->user()->team_id && $user->tasks->where('status','assigned')->count()==0  && $user->role != "leader")
                                    <form action="{{route('users.remove-team-member',$user->id)}}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="mb-3 btn btn-danger btn-sm">Remove from Team</button>
                                    </form>
                                @endif
                                <form action="{{route('users.details',$user->id)}}" method="POST">
                                    @csrf
                                    <button type="submit" class="btn btn-primary btn-sm">View Details</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        {{ $users->links()}}
    </div>
@endsection