routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home','HomeController@index')->name('dashboard.index')->middleware('auth');

Auth::routes();
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');








Route::middleware(['auth'])->group(function(){
Route::get('/dashboard','HomeController@index')->name('dashboard.index');

Route::resource('teams','TeamsController');


Route::resource('users','UsersController')->middleware(['leader']);
Route::post('users/details/{user}','UsersController@details')->name('users.details')->middleware(['leader']);
Route::put('/users/{user}/make-team-member','UsersController@makeTeamMember')->name('users.make-team-member')->middleware(['leader']);
Route::put('/users/{user}/remove-team-member','UsersController@removeTeamMember')->name('users.remove-team-member')->middleware(['leader']);
// Route::resource('teams','TeamsController');

Route::resource('tasks','TasksController');
// Route::get('/mytasks','TasksController@mytasks')->name('tasks.mytasks');
Route::get('/review','TasksController@review')->name('tasks.review')->middleware(['leader']);
// Route::get('/completed/{task}','TasksController@completed')->name('tasks.completed');
Route::get('/resolved/{task}','TasksController@resolved')->name('tasks.resolved')->middleware(['leader']);
Route::get('/unresolved/{task}','TasksController@unresolved')->name('tasks.unresolved')->middleware(['leader']);
Route::post('/tasks/{task}','TasksController@update')->name('tasks.update')->middleware(['leader']);
Route::post('/tasks/assigned/{user}','TasksController@assign')->name('tasks.assign')->middleware(['leader']);
Route::get('/mytasks','TasksController@mytasks')->name('tasks.mytasks');
Route::get('/completed/{task}','TasksController@completed')->name('tasks.completed');
Route::get('/reassign/{task}','TasksController@reassign')->name('tasks.reassign');
Route::get('/poll','TasksController@poll')->name('tasks.poll');
Route::get('/giveup/{task}','TasksController@giveup')->name('tasks.giveup');
Route::get('/claim-task/{task}','TasksController@claim')->name('tasks.claim');
});


?>

resources/views/dashboard/partials/_dashboard-content.blade.php
 <!-- Content Row -->
 <div class="row">

<!-- Earnings (Monthly) Card Example -->
@if(auth()->user()->role == 'member')
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">All Tasks</div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{auth()->user()->tasks->count()}}</div>
        </div>
        <div class="col-auto">
          <i class="fas fa-calendar fa-2x text-gray-300"></i>
        </div>
      </div> 
    </div>
  </div>
</div>

<!-- Earnings (Monthly) Card Example -->
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-success shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Completed Tasks</div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{auth()->user()->tasks->where('status','resolved')->count()}}</div>
        </div>
        <div class="col-auto">
          <i class="fa fa-check-circle fa-2x text-gray-300"></i>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Earnings (Monthly) Card Example -->
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-info shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Active Tasks</div>
          <div class="row no-gutters align-items-center">
            <div class="col-auto">
              <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{auth()->user()->tasks->where('status','assigned')->count()}}</div>
            </div>
            
          </div>
        </div>
        <div class="col-auto">
          <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Pending Requests Card Example -->
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-warning shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Failed Tasks</div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{{auth()->user()->tasks->where('status','unresolved')->count()}}</div>
        </div>
        <div class="col-auto">
          <i class="fas fa-exclamation-triangle  fa-2x text-gray-300"></i>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<!-- Content Row -->
@endif
<div class="row">






<!-- Area Chart -->
<div class="col-xl-4 col-lg-7">

<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary text-center">Employee of the Month </h6>
     
    </div>
    <!-- Card Body -->
    <div class="card-body">
      <div class="content text-center">
       <div class="icon wow rotateIn"><i class="fa fa-star fa-4x text-warning text-center mb-4"></i></div>

        <h3 class="text-center font-weight-bold text-warning mb-3">{{$users[0]->name}}</h3>
        <h6>Team : {{$users[0]->team->name}}</h6>
      </div>
    </div>
    
  </div>


 


  
</div>

<div class="col-xl-4">

<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary text-center">Leader of the Month </h6>
     
    </div>
    <!-- Card Body -->
    <div class="card-body">
      <div class="content text-center">
       <div class="icon wow bounceIn"><i class="fa fa-user-tie fa-4x text-center mb-4" style="color:darksalmon;"></i></div>

        <h3 class="text-center font-weight-bold  mb-3" style="color: darksalmon;">{{$leader->name}}</h3>
        <h6>Team : {{$leader->team->name}}</h6>
      </div>
    </div>
    
  </div>
</div>


<div class="col-xl-4 col-lg-5">
  <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Awards</h6>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      <div class="row">
      
      @foreach($users as $user)
        
        <div class="col-md-8 mb-3">
        
          <p class="{{$users[0] === $user ? 'text-warning font-weight-bold' : ''}} ">{{$user->name}}</p>
        </div>
        
        <div class="col-md-4 mb-3">
        @if(($users[0] == $user) || ($users[1] == $user) || ($users[2] == $user))
        @if($users[0] === $user)
          <div class="col-md-12">
         
          <i class="fa fa-trophy fa-2x fas text-warning wow fadeIn"></i>
         
          </div>
          @endif

          @if($users[1] === $user)
          <div class="col-md-12">
         
          <i class="fa fa-trophy fa-2x fas wow fadeIn" style="color:darkgrey"></i>
         
          </div>
          @endif

          @if($users[2] === $user)
          <div class="col-md-12">
         
          <i class="fa fa-trophy fa-2x fas wow fadeIn"style="color:#b08d57;"></i>
         
          </div>
         @endif
         @else

         
          <div class="col-md-12">
         
        
          </div>
          @endif
        </div>
        
        @endforeach
      </div>
      
    </div>
    
  </div>

</div>

<!-- Pie Chart -->

</div>

<!-- Content Row -->
<div class="row">

<!-- Content Column -->
@if(!auth()->user()->isLeader())
<div class="col-lg-12 mb-4">

  <!-- Project Card Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Task Pole</h6>
    </div>
    <div class="card-body">
          <div class="row mb-3">
            <div class="col-md-4 font-weight-bold text-primary">Task Name</div>
            <div class="col-md-2 font-weight-bold text-primary">Level</div>
            <div class="col-md-4 font-weight-bold text-primary">Due On</div>
    </div>
        @foreach($polltasks as $polltask)
          <div class="row mb-2">
            <div class="col-md-4">{{$polltask->name}}</div>
            @if($polltask->level == 0)
              <div class="col-md-2">Easy</div>
            @elseif($polltask->level == 1)
              <div class="col-md-2">Intermediate</div>
            @elseif($polltask->level == 2)
              <div class="col-md-2">Difficult</div>
            @endif
            <div class="col-md-4">{{$polltask->due_on}}</div>
            <a href="{{route('tasks.claim',$polltask->id)}}" class="btn btn-sm p-0 btn-primary text-sm col-md-2">Claim</a>
          </div>
        @endforeach
    </div>
  </div>

</div>
@endif

<div class="col-lg-6 mb-4">

  <!-- Illustrations -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
    </div>
    <div class="card-body">
      <div class="text-center">
        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{{ asset('assets/img/undraw_posting_photo.svg')}}" alt="">
      </div>
      <p>Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>
      <a target="_blank" rel="nofollow" href="https://undraw.co/">Browse Illustrations on unDraw &rarr;</a>
    </div>
  </div>
</div>

  <!-- Approach -->
  <div class="col-lg-6 mb-4">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Development Approach</h6>
    </div>
    <div class="card-body">
      <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce CSS bloat and poor page performance. Custom CSS classes are used to create custom components and custom utility classes.</p>
      <p class="mb-0">Before working with this theme, you should become familiar with the Bootstrap framework, especially the utility classes.</p>
    </div>
  </div>

</div>
</div>

resources/views/dashboard/partials/_footer.blade.php
<footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>

resources/views/dashboard/partials/_logout-modal.blade.php
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ route('logout') }}"
          onclick="event.preventDefault();
          document.getElementById('logout-formm').submit();"
          >
          <form id="logout-formm" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
          </form>
            Logout
          </a>
        </div>
      </div>
    </div>
  </div>

resources/views/dashboard/partials/_message.blade.php
<div class="row">
    <div class="col-md-12">
        @if(session()->has('success'))
            <div class="alert alert-success alert-dismissable fade show" role="alert">
                {{session()->get('success')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif

        @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissable fade show" role="alert">
                {{session()->get('error')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @endif
        
    </div>
</div>

resources/views/dashboard/partials/_navigation.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                    <div class="small text-gray-500">Emily Fowler · 58m</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                    <div class="status-indicator"></div>
                  </div>
                  <div>
                    <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                    <div class="small text-gray-500">Jae Chun · 1d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                    <div class="status-indicator bg-warning"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Chicken the Dog · 2w</div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>

resources/views/dashboard/partials/_sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{route('dashboard.index') }}">
    <div class="sidebar-brand-icon">
        <i class="fas fa-paper-plane"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Ticket Management</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
    <a class="nav-link" href="{{ route('dashboard.index')}}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
    Interface
    </div>

    @if(auth()->user()->isLeader())
    <!-- Nav Item - Users  Menu -->
    <li class="nav-item {{ $sidebarSection =='users' ? 'active' : ''}}">
    <a class="nav-link" href="{{ route('users.index')}} " >
        <i class="fas fa-fw fa-user-tie"></i>
        <span>Users</span>
    </a>
    </li>
    @endif

    <!-- Nav Item - Teams Menu -->

    <li class="nav-item {{ $sidebarSection =='teams' ? 'active' : ''}}">
    <a class="nav-link" href="{{route('teams.index')}}" >
        <i class="fas  fa-fw fa-users"></i>
        <span>Team</span>
    </a>
    </li>

   
   
    @if(!auth()->user()->isLeader())
    <!-- Nav Item - Tasks Menu -->
    <li class="nav-item {{ $sidebarSection =='tasks' ? 'active' : ''}}">
    <a class="nav-link" href="{{ route('tasks.mytasks') }}" >
        <i class="fas fa-fw fa-tasks"></i>
        <span>Tasks</span>
    </a>
    </li> 
    @endif
    @if(auth()->user()->isLeader())
    <li class="nav-item {{ $sidebarSection =='tasks' ? 'active' : ''}}">
    <a class="nav-link collapsed" 
        href="" data-toggle="collapse" 
        data-target="#collapseTasks" 
        aria-expanded="true" 
        aria-controls="collapseTasks">
        <i class="fas fa-fw fa-tasks"></i>
        <span>Tasks</span>
    </a>
    <div id="collapseTasks" 
        class="collapse {{ $sidebarSection=='tasks' ? 'show' : ''}}" 
        aria-labelledby="headingTasks" 
        data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item {{$sidebarSubSection=='add-tasks' ? 'active' : ''}}" 
            href="{{ route('tasks.create') }}">Assign Task</a>
        <a class="collapse-item {{$sidebarSubSection=='poll-tasks' ? 'active' : ''}}" 
            href="{{ route('tasks.poll') }}">Make Task Poll</a>
        <a class="collapse-item {{$sidebarSubSection=='manage-tasks' ? 'active' : ''}}" 
            href="{{ route('tasks.index') }}">Manage Tasks</a>
        <a class="collapse-item {{$sidebarSubSection=='review-tasks' ? 'active' : ''}}" 
        href="{{ route('tasks.review') }}">Review Tasks</a>
     
    </div>
    @endif
    </li>

    

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading 
    <div class="sidebar-heading">
    Addons
    </div>

    Nav Item - Pages Collapse Menu 
    <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
        <i class="fas fa-fw fa-folder"></i>
        <span>Pages</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Login Screens:</h6>
        <a class="collapse-item" href="login.html">Login</a>
        <a class="collapse-item" href="register.html">Register</a>
        <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
        <div class="collapse-divider"></div>
        <h6 class="collapse-header">Other Pages:</h6>
        <a class="collapse-item" href="404.html">404 Page</a>
        <a class="collapse-item" href="blank.html">Blank Page</a>
        </div>
    </div>
    </li>

    Nav Item - Charts 
    <li class="nav-item">
    <a class="nav-link" href="charts.html">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Charts</span></a>
    </li>

    Nav Item - Tables 
    <li class="nav-item">
    <a class="nav-link" href="tables.html">
        <i class="fas fa-fw fa-table"></i>
        <span>Tables</span></a>
    </li> 

    Divider
    <hr class="sidebar-divider d-none d-md-block"> -->

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>