routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home','HomeController@index')->name('dashboard.index')->middleware('auth');

Auth::routes();
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');








Route::middleware(['auth'])->group(function(){
Route::get('/dashboard','HomeController@index')->name('dashboard.index');

Route::resource('teams','TeamsController');


Route::resource('users','UsersController')->middleware(['leader']);
Route::post('users/details/{user}','UsersController@details')->name('users.details')->middleware(['leader']);
Route::put('/users/{user}/make-team-member','UsersController@makeTeamMember')->name('users.make-team-member')->middleware(['leader']);
Route::put('/users/{user}/remove-team-member','UsersController@removeTeamMember')->name('users.remove-team-member')->middleware(['leader']);
// Route::resource('teams','TeamsController');

Route::resource('tasks','TasksController');
// Route::get('/mytasks','TasksController@mytasks')->name('tasks.mytasks');
Route::get('/review','TasksController@review')->name('tasks.review')->middleware(['leader']);
// Route::get('/completed/{task}','TasksController@completed')->name('tasks.completed');
Route::get('/resolved/{task}','TasksController@resolved')->name('tasks.resolved')->middleware(['leader']);
Route::get('/unresolved/{task}','TasksController@unresolved')->name('tasks.unresolved')->middleware(['leader']);
Route::post('/tasks/{task}','TasksController@update')->name('tasks.update')->middleware(['leader']);
Route::post('/tasks/assigned/{user}','TasksController@assign')->name('tasks.assign')->middleware(['leader']);
Route::get('/mytasks','TasksController@mytasks')->name('tasks.mytasks');
Route::get('/completed/{task}','TasksController@completed')->name('tasks.completed');
Route::get('/reassign/{task}','TasksController@reassign')->name('tasks.reassign');
Route::get('/poll','TasksController@poll')->name('tasks.poll');
Route::get('/giveup/{task}','TasksController@giveup')->name('tasks.giveup');
Route::get('/claim-task/{task}','TasksController@claim')->name('tasks.claim');
});


?>

app/Task.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Console\Scheduling\Schedule;
use App\Console\Kernel as ConsoleKernal;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['name','status','assigned_on','due_on','completed_on','level','user_id'];

    public function user()
    {
        return $this->belongsTo(\App\User::class);
    }
    public function team()
    {
        return $this->belongsTo(\App\Team::class);
    }
    public function getAssignedDateAttribute(){
        return (Carbon::parse($this->assigned_on))->diffForHumans();
    } 
    public function getDueDateAttribute(){
        return (Carbon::parse($this->due_on))->diffForHumans();
    } 
    public function getCompletedDateAttribute(){
        return (Carbon::parse($this->completed_on))->diffForHumans();
    } 
      
    
    
    public function updateUserEfficiency(User $user , int $points){
        $user->efficiency = $user->efficiency+$points;
        $user->save();
        
    }

    public function updateLeaderEfficiency(User $leader,Task $task){
        
        if($task->level == 0 )
            $points = 1;
        else if($task->level==1)
            $points = 2;
        else if($task->level ==2)
            $points =3;

        $leader->efficiency = $leader->efficiency+$points;
        $leader->save();
    }

    public function giveupEfficiency(User $user,Task $task)
    {
        if($task->level==0)
            $points = 6;
        else if($task->level==1)
            $points = 10;
        else if($task->level == 2)
            $points = 13;

        $user->efficiency = $user->efficiency - $points;
        $user->save();
    }

    public function getEfficientUser(){
        
        $users = User::orderBy("efficiency",'DESC')->where('team_id',auth()->user()->team_id)->where('role','member')->get();
        $newEfficiencyArray = array();
        foreach ($users as $user) {
            $flag = true;
            $totalHours = 0;
            $count = 0;
            $task = Task::all()->where('user_id',$user['id'])->where('status','assigned')->pluck('level');
            
            if($task->count() == 0)
            {
                $eligible = Carbon::now()->diffInDays(Carbon::parse($user->created_at));
                if($eligible >= 30){
                    return $user;   
                }
                $flag = false;            
            }
            
            elseif($flag){
                for($i = 0;$i < $task->count() ; $i++){
                    $level = $task[$i];
                    if($level == 0){$totalHours += 1;}
                    elseif($level == 1){$totalHours += 2;}
                    elseif($level == 2){$totalHours += 3;}
                
                    $newEfficiency = $user['efficiency']/$totalHours;
                    array_push($newEfficiencyArray,$newEfficiency);
                }
            }
        } 
        $userFinal = array_search(max($newEfficiencyArray),$newEfficiencyArray);
        return $users[$userFinal];   
        
    }
    

}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Task\CreateTaskRequest;
use App\Http\Requests\Task\UpdateTaskRequest;
use App\Notifications\AssignedTask;
use App\Notifications\CompletedTask;
use App\Notifications\GaveUpTask;
use App\Notifications\GaveUpTaskMember;
use App\Notifications\ResolvedTask;
use App\Notifications\UnresolvedTask;
use App\Task;
use App\User;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\TaskHelper;
use Illuminate\Http\Request;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::whereIn('user_id', function($query){
            $query->select('id')
            ->from(with(new User)->getTable())
            ->whereIn('id',User::all()->where('team_id',auth()->user()->team_id)->pluck('id')->toArray());
        })->orderBy('updated_at','DESC')->get();
        $sidebarSubSection = "manage-tasks";
        $sidebarSection = "tasks";
        return view('tasks.index',compact([
            'tasks',
            'sidebarSection',
            'sidebarSubSection'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $assigned=0;
        $users = User::all()->where('team_id',auth()->user()->team_id)->where('role','member');
        $sidebarSubSection = "add-tasks";
        $sidebarSection = "tasks";
        return view('tasks.create',compact([
            'users',
            'assigned',
            'sidebarSection',
            'sidebarSubSection'
        ]));
    }

    public function reassign(Task $task)
    {
        
        $assigned=2;
        $users = User::all()->where('team_id',auth()->user()->team_id);
        $restrictedUser=User::all()->where('id',$task->user_id)->pluck('id')[0];
        
        $sidebarSubSection = "manage-tasks";
        $sidebarSection = "tasks";
        
        $user = $task->user;
        $user->notify(new UnresolvedTask($task)); 
        return view('tasks.reassign',compact([
            'users',
            'task',
            'assigned',
            'restrictedUser',
            'sidebarSection',
            'sidebarSubSection'
        ]));
    }

   

    public function store(CreateTaskRequest $request)
    {
       
        $task = Task::create([
           'name'=>$request->name,
           'level'=>$request->level,
           'status'=>$request->status,
            'assigned_on'=>$request->assigned_on,
            'due_on'=>$request->due_on,
            'user_id'=>$request->user_id
        ]);
        if($request->user_id != NULL){
            $user = User::all()->where('id',$request->user_id)->first();
            $user->notify(new AssignedTask($task));
            session()->flash('success','Task Assigned Successfully');
            return redirect(route('tasks.index'));
        }
        
        return redirect(route('dashboard.index'));

    }    
   
    public function assign(User $user)
    {     
        
        $assigned=1;
        $sidebarSection = "tasks";
        $sidebarSubSection = "add-tasks";
         return view('tasks.create',compact([
             'user',
             'assigned',
             'sidebarSection',
            'sidebarSubSection'
         ]));
         
    }
    public function poll()
    {     
        $sidebarSection = "tasks";
        $sidebarSubSection = "poll-tasks";
         return view('tasks.poll',compact([
             'sidebarSection',
            'sidebarSubSection'
         ]));
         
    }
    public function review()
    {     
        $tasks = Task::whereIn('user_id', function($query){
            $query->select('id')
            ->from(with(new User)->getTable())
            ->whereIn('id',User::all()->where('team_id',auth()->user()->team_id)->pluck('id')->toArray());
        })->orderBy('updated_at','DESC')->get();
        $sidebarSection = "tasks";
        $sidebarSubSection = "review-tasks";
         return view('tasks.review',compact([
             'tasks',
             'sidebarSection',
            'sidebarSubSection'
         ]));
         
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        $user = User::all()->where('id',$task->user_id)->first();
        // dd($users);
        // $restrictedUser=User::where('id',$task->user_id);
        $sidebarSection = "tasks";
        $sidebarSubSection = "manage-tasks";

        
        return view('tasks.edit',compact([
            'task',
            'user',
            'sidebarSection',
            'sidebarSubSection'
        ]));
    }

    public function mytasks()
    {
        $tasks = Task::latest('updated_at')->where('user_id',auth()->user()->id)->paginate(10);
        $sidebarSection = "tasks";
        $sidebarSubSection = "my-tasks";
        return view('tasks.mytasks',compact([
            'tasks',
            'sidebarSection',
            'sidebarSubSection'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTaskRequest $request, Task $task)
    {
        
        $data = $request->only(['name','user_id','level','status','assigned_on','due_on']);
       
        $task->update($data);
        session()->flash('success','Task Updated Successfully!');
        return redirect(route('tasks.index'));
    }

    public function claim(Task $task)
    {
        $task->update(['user_id'=>auth()->id(),'status'=>'assigned']);
        $task->save();
        session()->flash('success','Task claimed Successfully!');
        return redirect(route('dashboard.index'));
    }
    
 
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //

    }

    public function completed(Task $task)
    {
       
        $task->status = "completed";
        $task->completed_on = now();
        $task->save();
        
        $user = User::all()->where('team_id',auth()->user()->team_id)->where('role','leader')->first();
        
        $user->notify(new CompletedTask($task));
        return redirect(route('tasks.mytasks'));

    }
   
    public function resolved(Task $task)
    {
        
        $task->updateUserEfficiency($task->user,TaskHelper::getPoints($task));
        $task->updateLeaderEfficiency(auth()->user(),$task);
        $task->status = "resolved";
        $task->save();
       
        $user = $task->user;
        $user->notify(new ResolvedTask($task));
        return redirect(route('tasks.review'));

        
    }

    public function unresolved(Task $task)
    {
        $task->status = "unresolved";
        $task->save();
       
        $user = $task->user;
        $user->notify(new UnresolvedTask($task));
        return redirect(route('tasks.review'));

        
    }
    public function giveup(Task $task)
    {
        $task->giveupEfficiency($task->user,$task);
        $task->status = "unresolved";
        $task->save();

        $user = User::all()->where('team_id',auth()->user()->team_id)->where('role','leader')->first();
        $member = $task->user;
        $user->notify(new GaveUpTask($task));
        $member->notify(new GaveUpTaskMember($task));
        
        return redirect(route('tasks.mytasks'));
    }
}

resources/views/tasks/create.blade.php
@extends('dashboard.layout')

@section('main-content')
    <div class="card">
        <div class="card-header">Add Task</div>
        <div class="card-body">
            <form action="{{ route('tasks.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Task Name</label>
                    <input type="text"
                           value="{{ old('name') }}"
                           class="form-control @error('name') is-invalid @enderror"
                           name="name" id="name">
                    @error('name')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                
                @if(!$assigned)
                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" value="" id="bestUser">
                    <label class="form-check-label" for="bestUser">
                    Assign Task Automatically </label>
                </div>
                @endif

                
                <div class="form-group">
                    <label for="user_id">Assign to : </label>
                    <select name="user_id" id="user_id" class="form-control select2">
                    @if(!$assigned)
                        @foreach($users as $user)
                            
                            <option value="{{$user->id}}">{{$user->name}}</option>
                           
                        @endforeach
                    @else
                         
                            <option value="{{$user->id}}" selected>{{$user->name}}</option>
                      
                    @endif;

                  
                    </select>
                </div>


                <div class="form-group">
                    <label for="status">Status</label>
                    <select name="status" id="status" class="form-control select2">
                        <option value="assigned" selected>Assigned</option>
                        <option value="unresolved" disabled>Unresolved</option>
                        <option value="completed" disabled>Completed</option>
                        <option value="resolved" disabled>Resolved</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="level">Level</label>
                    <select name="level" id="level" class="form-control select2">
                        <option value="0">Easy</option>
                        <option value="1">Intermediate</option>
                        <option value="2">Difficult</option>
                        
                    </select>
                </div>

                <div class="form-group">
                    <label for="assigned_on">Assigned On</label>
                    <input type="date"
                           value="{{ old('assigned_on')}}"
                           class="form-control"
                           name="assigned_on" id="assigned_on" >
                </div>


                <div class="form-group">
                    <label for="due_on">Due On</label>
                    <input type="date"
                           value="{{ old('due_on') }}"
                           class="form-control"
                           name="due_on" id="due_on">
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Assign Task</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('page-level-scripts')

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        var level = document.getElementById('level');
        
        flatpickr("#assigned_on", {
            enableTime: true,    
            minDate:new Date(),
            defaultDate:new Date()        
        });

        
        var assigned_on =document.getElementById('assigned_on');
        var a = new Date(assigned_on.value); 

        flatpickr("#due_on", {
            enableTime: true,
            minDate:new Date(assigned_on.value).fp_incr((parseInt(level.value)+1)),
            defaultDate:new Date(assigned_on.value).setDate(a.getDate() + (parseInt(level.value)+1))      
            
        });

        function setValue(){
            flatpickr("#due_on", {
            enableTime: true,
            defaultDate:new Date(assigned_on.value).setDate(a.getDate()+ (parseInt(level.value)+1)),
            minDate: new Date(assigned_on.value).setDate(a.getDate()+ (parseInt(level.value)+1))
            });
            
        }
        
        assigned_on.addEventListener('change',function(){
            setValue();
        });
        level.addEventListener('change',function(){
           setValue();
        }); 


        var assign_to = document.getElementById('bestUser');
        var assign_list = document.getElementById('user_id');
        function assignTask(){
            if(assign_to.checked == true){
                
                <?php
                    use App\Task;
                    $task = new Task();
                    $user = $task->getEfficientUser();
                ?>
                assign_list.innerHTML = `<option value="<?=$user->id?>" selected><?=$user->name?></option>`
            }
            else{
                assign_list.innerHTML = "";
                <?php
                    foreach($users as $user)
                    {?>
                        assign_list.innerHTML += `<option value="<?=$user->id?>" selected><?=$user->name?></option>`
                    <?php
                    }
                    ?>

            }
        }

        assign_to.addEventListener('change',function(){
            assignTask();
        });
    </script>

     
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.3/select2_locale_ar.min.js"></script>
@endsection
@section('page-level-styles')

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.3/select2-bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.3/select2.min.css">
@endsection

resources/views/tasks/index.blade.php
@extends('dashboard.layout')
@section('title','Ticket Management')
@section('sub-title','Users')

@section('main-content')

<div class="d-flex justify-content-end mb-3">
    <a href="{{route('tasks.create')}}" class="btn btn-primary">Add Task</a>
</div>

    <div class="card">
        <div class="card-header">Manage Tasks :  </div>

        <div class="card-body">
            <table class="table table-bordered table-responsive">
                <thead>
                   
                    <th>Name</th>
                    <th>Assigned To</th>
                    <th>Level</th>
                    <th>Status</th>
                    <th>Assigned On</th>
                    <th>Due On</th>    
                    <th>Completed On</th>                
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($tasks as $task)
                        <tr>
                           
                            <td>
                                {{$task->name}}
                            </td>
                            <td>
                                {{$task->user->name}}
                            </td>
                            
                            <td>
                                @if($task->level==0)
                                    Easy
                                @elseif($task->level==1)
                                    Intermediate
                                @else
                                    Difficult
                                @endif
                            </td>
                            <td>
                                {{$task->status}}
                            </td>
                            
                            <td>
                                {{$task->assigned_date}}
                            </td>

                            <td>
                                {{$task->due_date}}
                            </td>

                            <td>
                            @if(($task->status=="assigned" || !$task->status=='unresolved') && !$task->completed_on )
                                    In Progress
                            @elseif($task->status=="unresolved") 
                                    <p class="text-danger">Failed!</p> 
                            @else
                                    {{$task->completed_date}}
                            @endif 
                            </td>
                            
                            <td>
                                @if($task->status=='assigned'||!$task->status=='unresolved')
                                <a href="{{route('tasks.edit',$task->id)}}" class="btn btn-sm btn-primary" >Edit</a>
                                @elseif($task->status=='completed')
                                <a href="{{route('tasks.review')}}" class="btn btn-outline-primary btn-sm">Review</a>
                              @endif
                              
                            </td>
                        </tr>
                    @endforeach
                    
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/tasks/mytasks.blade.php
@extends('dashboard.layout')
@section('title','Ticket Management')
@section('sub-title','Users')

@section('main-content')

<div class="d-flex justify-content-end mb-3">
    <a href="{{route('tasks.create')}}" class="btn btn-primary">Add Task</a>
</div>

    <div class="card">
        <div class="card-header">My Tasks :  </div>

        <div class="card-body">
            <table class="table table-bordered table-responsive">
                <thead>
                   
                    <th>Name</th>
                    
                    <th>Level</th>
                    <th>Status</th>
                    <th>Assigned On</th>
                    <th>Due On</th>    
                    <th>Completed On</th>                
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($tasks as $task)
                        <tr>
                           
                            <td>
                                {{$task->name}}
                            </td>
                            
                            
                            <td>
                                @if($task->level==0)
                                    Easy
                                @elseif($task->level==1)
                                    Intermediate
                                @else
                                    Difficult
                                @endif
                            </td>
                            <td>
                                {{$task->status}}
                            </td>
                            
                            
                            <td class= "{{Carbon\Carbon::now()->gt(Carbon\Carbon::parse($task->due_on)) ? 'text-danger' : ''}}">
                                {{$task->assigned_date}}
                            </td>

                            <td class="{{Carbon\Carbon::now()->gt(Carbon\Carbon::parse($task->due_on)) ? 'text-danger' : ''}} ">
                                <div id="simple_timer<?=$task['id']?>" >
                                   
                                </div>
                            </td>

                            <td>
                             
                                @if(($task->status=="assigned" || !$task->status=='unresolved') && !$task->completed_on )
                                    In Progress
                                @elseif($task->status=="unresolved") 
                                    <p class="text-danger">Failed!</p> 
                                    @else
                                    {{$task->completed_date}}
                                @endif 
                            </td> 
                            
                            <td>
                             
                            @if($task->status=='assigned')
                                <a href="{{route('tasks.completed',$task->id)}}" class="btn btn-sm  {{Carbon\Carbon::now()->gt(Carbon\Carbon::parse($task->due_on)) ? 'btn-danger' : 'btn-primary'}}" >Complete</a>

                                <a href="{{route('tasks.giveup',$task->id)}}" class="btn btn-sm btn-warning" >Give Up</a>
                            @endif
                              
                            </td>
                        </tr>
                    @endforeach
                    
                </tbody>
            </table>
        </div>
        {{$tasks->links()}}
    </div>
@endsection
@section('page-level-styles')
<link rel="stylesheet" href="{{asset('assets/timer/resources/default.css')}}">
@endsection
@section('page-level-scripts')
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="{{asset('assets/timer/build/jquery.syotimer.js')}}"></script>
<script src="{{asset('assets/timer/build/jquery.syotimer.min.js')}}"></script>

<script>
    
    <?php
    foreach($tasks as $task){
        if($task['status'] == "assigned"){ 
           ?>
    $('#simple_timer<?=$task['id']?>').syotimer({
        year: new Date("<?=$task['due_on']?>").getFullYear(),
        month: (new Date("<?=$task['due_on']?>").getMonth() + 1),
        day: new Date("<?=$task['due_on']?>").getDate(),
        hour:new Date("<?=$task['due_on']?>").getHours(),
        minute:new Date("<?=$task['due_on']?>").getMinutes()
    });
<?php } }  ?>
    
     
</script>



@endsection

resources/views/tasks/review.blade.php
@extends('dashboard.layout')
@section('title','Ticket Management')
@section('sub-title','Users')

@section('main-content')

<div class="d-flex justify-content-end mb-3">
    <a href="{{route('tasks.create')}}" class="btn btn-primary">Add Task</a>
</div>

    <div class="card">
        <div class="card-header">My Tasks :  </div>

        <div class="card-body">
            <table class="table table-bordered table-responsive">
                <thead>
                   
                    <th>Name</th>
                    <th>Level</th>
                    <th>Status</th>
                    <th>Assigned To</th>
                    <th>Assigned On</th>
                    <th>Due On</th>                  
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($tasks as $task)
                        <tr>
                           
                            <td>
                                {{$task->name}}
                            </td>
                            
                            
                            <td>
                                @if($task->level==0)
                                    Easy
                                @elseif($task->level==1)
                                    Intermediate
                                @else
                                    Difficult
                                @endif
                            </td>
                            <td>
                                {{$task->status}}
                            </td>
                            <td>
                                {{$task->user->name}}
                            </td>
                            
                            <td>
                                {{$task->assigned_date}}
                            </td>

                            <td>
                                {{$task->due_date}}
                            </td>
                            <td>
                             
                            @if($task->status=='completed')
                                <a href="{{route('tasks.resolved',$task->id)}}" class="btn btn-sm btn-outline-primary" >Resolve</a>
                                <a href="{{route('tasks.unresolved',$task->id)}}" class="btn btn-sm btn-outline-primary" >Reject</a>
                            @elseif( $task->status=='unresolved')
                            <a href="{{route('tasks.reassign',$task->id)}}" class="btn btn-sm btn-outline-danger" >Re-Assign</a>
                            @endif
                              
                            </td>
                        </tr>
                    @endforeach
                    
                </tbody>
            </table>
        </div>
       
    </div>
@endsection
@section('page-level-scripts')


@endsection